# Generated by Django 5.2.4 on 2025-07-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Age', models.IntegerField(null=True)),
                ('DateofBirth', models.DateField(null=True)),
                ('Class', models.TextField(null=True)),
            ],
        ),
    ]
