# Generated by Django 5.2.4 on 2025-08-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_studentmodel_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='studentRoll',
            field=models.IntegerField(null=True),
        ),
    ]
