# Generated by Django 5.2.4 on 2025-08-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_studentmodel_studentroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
